version: "3"

services:
  php-cli:
    build:
      context: docker
    working_dir: /app
    environment:
      PHP_IDE_CONFIG: "serverName=number-systems"
    volumes:
      - ./:/app
      - ${SSH_PRIVATE_KEY_PATH}:/root/.ssh/id_rsa
